name: Deploy Next.js to Oracle VPS

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: 80.225.203.193
          username: ubuntu
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            if [ "${{ github.ref }}" == "refs/heads/main" ]; then
              cd /home/ubuntu/urbanbullet-site
              git pull origin main
              rm -rf .next
              npm install
              npm run build
              pm2 restart urbanbullet
            elif [ "${{ github.ref }}" == "refs/heads/dev" ]; then
              cd /home/ubuntu/urbanbullet-site-dev
              git pull origin dev
              rm -rf .next
              npm install
              npm run build
              pm2 restart urbanbullet-dev
            fi
